[[constraint]]
  name = "github.com/godbus/dbus"
  version = "5.0.3"

[[constraint]]
  name = "github.com/gorilla/websocket"
  version = "1.4.1"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.4.2"

[[constraint]]
  branch = "master"
  name = "gitpct.epam.com/epmd-aepr/aos_common"
  source = "git@gitpct.epam.com:epmd-aepr/aos_common.git"
